// <auto-generated />
using System;
using GTLabs.Identity.Authorization.Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GTLabs.Identity.Authorization.Infrastructure.Migrations
{
    [DbContext(typeof(AuthorizationDbcontext))]
    [Migration("20251205013856_AdicaoCascadeBehavior")]
    partial class AdicaoCascadeBehavior
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GTLabs.Identity.Authorization.Domain.Apps.Entities.App", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_time");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleter_id");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletion_time");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("identifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modification_time");

                    b.Property<Guid?>("ModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("modifier_id");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("route");

                    b.HasKey("Id")
                        .HasName("p_k_app");

                    b.ToTable("app");
                });

            modelBuilder.Entity("GTLabs.Identity.Authorization.Domain.Apps.Entities.AppPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AppId")
                        .HasColumnType("uuid")
                        .HasColumnName("app_id");

                    b.Property<DateTime?>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_time");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleter_id");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletion_time");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modification_time");

                    b.Property<Guid?>("ModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("modifier_id");

                    b.Property<Guid>("PermittedAppId")
                        .HasColumnType("uuid")
                        .HasColumnName("permitted_app_id");

                    b.HasKey("Id")
                        .HasName("p_k_app_permission");

                    b.HasIndex("AppId");

                    b.HasIndex("PermittedAppId");

                    b.ToTable("app_permission");
                });

            modelBuilder.Entity("GTLabs.Identity.Authorization.Domain.Apps.Entities.AppPermission", b =>
                {
                    b.HasOne("GTLabs.Identity.Authorization.Domain.Apps.Entities.App", "App")
                        .WithMany("Permissions")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_app_permission_app_app_id");

                    b.HasOne("GTLabs.Identity.Authorization.Domain.Apps.Entities.App", "PermittedApp")
                        .WithMany("PermittedBy")
                        .HasForeignKey("PermittedAppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_app_permission_app_permitted_app_id");

                    b.Navigation("App");

                    b.Navigation("PermittedApp");
                });

            modelBuilder.Entity("GTLabs.Identity.Authorization.Domain.Apps.Entities.App", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("PermittedBy");
                });
#pragma warning restore 612, 618
        }
    }
}
